### ISSUE TITLE
more speed

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/eggd_GATKgCNV_call#11]
Downloading BAMs could probably be a lot quicker:

https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/2811e622e48a1e2bd48e82b785b5b8635dd3b039/src/GATK_gCNVcaller.sh#L56-L59

looks to take ~20 minutes from a random job, could be rewritten as `echo ${bambais[@]} | xargs -n1 -P$(nproc --all) dx download --no-progress` and hopefully would be much faster

**Comment by chrispyatt** [comment]
I've changed this to `echo ${bambais[@]} | jq -r '.["$dnanexus_link"]' | xargs -n1 -P$(nproc --all) dx download --no-progress -o inputs/bams/` in my multijob branch for wes cnvs. Haven't checked whether it's actually faster though.
